{{- if .Values.kedaScaledObject.enabled }}
{{- if not .Values.kedaScaledObject.authenticationRef.name }}
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: {{ .Release.Name }}-kafka-debounce
spec:
  secretTargetRef:
    - parameter: sasl
      name: {{ .Release.Name }}-kafka-debounce-keda-secrets
      key: sasl
    - parameter: username
      name: {{ .Release.Name }}-kafka-debounce-keda-secrets
      key: username
    - parameter: password
      name: {{ .Release.Name }}-kafka-debounce
      key: SASL_PASSWORD
    - parameter: tls
      name: {{ .Release.Name }}-kafka-debounce-keda-secrets
      key: tls
    - parameter: ca
      name: {{ .Values.kedaScaledObject.authenticationRef.caSecretName }}
      key: {{ .Values.kedaScaledObject.authenticationRef.caSecretKey }}
{{- end }}
{{- end }}