{{ if .Values.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-kafka-debounce
  {{- if .Values.podMonitor.labels }}
  labels:
  {{ toYaml .Values.podMonitor.labels | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-kafka-debounce
  podMetricsEndpoints:
  - port: main
{{ if .Values.podMonitor.sampleLimit }}
  sampleLimit: {{ .Values.podMonitor.sampleLimit }}
{{ end }}
{{ end }}